# Site settings
title: Jekyll Test
email: robotmachine+sid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/~robotmachine/" # the subpath of your site, e.g. /blog/
url: "http://silenceisdefeat.net" # the base hostname & protocol for your site
twitter_username: robotmachine
github_username:  robotmachine

# Build settings
markdown: kramdown
