# Site settings
title: "[ robot ] + [ machine ]"
email: robotmachine@gmail.com
description: >
    This is a place on the internet where someone you
    probably don't know writes words.
url: "https://robotmachine.github.io"
username: robotmachine

# Build settings
markdown: kramdown
